- data/birth-dates/14.txt
> git commit

- data/birth-dates/17.txt
Included the year in the file 17.txt
> Change in year of birth

- data/birth-dates/24.txt
see http://en.wikipedia.org/wiki/Ramon_Llull
> Add birthyear of Ramon Llull

- data/birth-dates/12.txt
Please add my changed birthdate to your repository.
Thanks.
> Added birthyear - Author: Andreas Folz

- data/birth-dates/20.txt
> Date of Birth for Niklaus With added

- data/birth-dates/15.txt
> changed data

- data/birth-dates/06.txt
> Benny upload 06

- data/birth-dates/14.txt
> Birthdate No. 14

- data/birth-dates/03.txt
i have added his birth date :)
> added the birthdate

- data/birth-dates/02.txt
specify the born year of the person who called "Charles Babbage".
> data birthdates text02

- README.md
- data/birth-dates/14.txt
Committer: unknown <D061567@WDFN30120191A.emea.global.corp.sap>
number 14 does his tasks
> test commit 14

- data/birth-dates/20.txt
Signed-off-by: Pascal Muth <pascalmuth08@gmail.com>
> Added birth date

- README.md
- data/birth-dates/17.txt
Added birth date and fixed typo
> Added birth date and fixed typo

- data/birth-dates/26.txt
Birth year of John Vincent Atanasoff added
> year added

- data/birth-dates/31.txt
corrected the birthdate of James Gosling
> James Gosling's Birthdate corrected

- doc/install-windows.md
@kba  Is that the correct branch to merge?
> Clarify the name of the bib-file

- data/birth-dates/20.txt
The date of birth has been entered!
> Replaced the date of birth

- data/birth-dates/09.txt
> 9: Birth date of Noam Chomsky added

- data/birth-dates/02.txt
> Changed by Teena

- data/birth-dates/22.txt
Birtdate for Gerard Salton added
> Added Birtdate 

- data/birth-dates/18.txt
My pull request for scientific research
> changed name of claude shannon

- data/birth-dates/16.txt
> birth-dates/16.txt

- data/birth-dates/15.txt
> #15 Sergei Alexejewitsch Lebedew

- data/birth-dates/17.txt
> Jahr eingefügt

- doc/LatexExample/testDocument.tex
* Move the `bibliographystlye` into the preambel (as it is usual)
* Delete tabs/intends
> Reorder and reformat LaTeX example

- data/birth-dates/14.txt
> student 14

- data/birth-dates/09.txt
Added the birth year of Noam Chomsky
> New Birth Year

- data/birth-dates/05.txt
> Student 05

- data/birth-dates/19.txt
> change the birth date

- data/birth-dates/08.txt
- data/birth-dates/09.txt
> naira ibrahim

- data/birth-dates/23.txt
Signed-off-by: MLH <marie-louise.haider@bib.uni-mannheim.de>
> Habe den Inhalt der Datei korrigiert

- data/birth-dates/06.txt
- doc/faq.md
> Change Date

- data/birth-dates/13.txt
I found the birth date of Gottlob Frege
> updated birthdate

- data/birth-dates/17.txt
> added birthdate Bertrand Russell #17

- data/birth-dates/19.txt
I added the birthday year.
Signed-off-by: Marie-Louise Haider <marie-louise.haider@bib.uni-mannheim.de>
> Changed birthday

- data/birth-dates/15.txt
> updated file 15.txt

- data/birth-dates/20.txt
Signed-off-by: Marie-Louise Haider <marie-louise.haider@bib.uni-mannheim.de>
> Changed the birthday

- doc/install-windows.md
We should merge this PR after we have reset the dates for the git exercise.
> Fix typos in install-windows.md

- data/birth-dates/31.txt
Exercise in Sci work course
Signed-off-by: Hadeel Behiry <hadeel.behiry@gmail.com>
> Changed the date of birth of James Gosling

- data/birth-dates/03.txt
empty line usage
Signed-off-by: Andreas Szlatki
> updated birthday of person 03

- data/birth-dates/19.txt
Sophie Wilson (born Roger Wilson): 1957 Leeds
Signed-off-by: GuidoD <anonymous email-adress>
> changes on the file 19.txt

- data/birth-dates/08.txt
Signed-off-by: svenhormann <hormann.sven@gmx.de>
> Vannevar Bush birthdate

- data/birth-dates/05.txt
Signed-off-by: maoconpa <maoconpa@mail.uni-mannheim.de>
> Added birthday date

- data/birth-dates/15.txt
> AlexNeumann15

- data/birth-dates/02.txt
This was my task in CS Course
Signed-off-by: Nils Richter <nilricht@mail.uni-mannheim.de>
> Edited the year

- data/birth-dates/14.txt
> Chen Zongqi changes 14.txt

- data/birth-dates/28.txt
> Add birthyear of Shannon Claude

- data/birth-dates/32.txt
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Added year of birth

- data/birth-dates/21.txt
Signed-off-by: Stela <stelameta1993@gmail.com>
> Adjusted the year of birth.

- data/birth-dates/01.txt
signed-off-by: Zhe Sun sunzhesz@yahoo.com
> Add the year of Birthday

- data/birth-dates/22.txt
> Added birthdate

- data/birth-dates/13.txt
Added birthday for Gottlob Frege
> Add birthdate for 13.txt

- data/birth-dates/25.txt
Please proceed with my request :-)
> Commit From 25, Koester Stefan

- data/birth-dates/27.txt
Signed-off-by: Hailian Hou <hhlvanilla@163.com>
> input birth year

- .idea/vcs.xml
> Delete .idea subfolder

- data/birth-dates/27.txt
> Added Date

- data/birth-dates/23.txt
> birthday changed in 23.txt

- data/birth-dates/21.txt
> Konrad Zuse Birthday

- data/birth-dates/16.txt
Signed-off-by: erdasheshi <erda.sheshi@yahoo.com>
> Edit year of birth for Leibniz

- data/birth-dates/19.txt
Adding the birth year of this old lady.
> modifying file 19

- data/birth-dates/33.txt
Signed-off-by: Hygerta Gurabardhi
> birthday of John von Neumann

- data/birth-dates/05.txt
Exercise of Scientific Research
> George Boole birth year found

- data/birth-dates/02.txt
Signed-off-by: Flavia Kristo <kristoflavia@gmail.com>
> Date of birth has been changed

- data/birth-dates/05.txt
> Nr 5 checkin

- data/birth-dates/04.txt
> birth-dates

- data/birth-dates/09.txt
> chomsky birth date

- data/birth-dates/08.txt
Please update the birth year for Vannevar Bush
> added right birth year for Vannevar Bush

- data/birth-dates/14.txt
Pull Request of Nicole Wesemeyer
> Change the birth date 14

- data/birth-dates/11.txt
according to [wikipedia](https://en.wikipedia.org/wiki/Edsger_W._Dijkstra)
> Student 11: add birth year

- data/birth-dates/10.txt
> addBirthYear

- data/birth-dates/25.txt
Added birth date to Studentnr 25
> Added birth date to Studentnr 25

- data/birth-dates/09.txt
- Corrects Birthdate in data/birth-dates/09.txt
> Birthdate 09

- data/birth-dates/02.txt
> Added birthyear for Charles Babbage

- data/birth-dates/05.txt
Signed-off-by: Arthur Wonenberg <awonenbe@mail.uni-mannheim.de>
> Date Birth

- data/birth-dates/20.txt
please accept I did really important changes to the 20.txt file. I basically put the correct birth year of Nikolaus Wirth. Very important!!!
> Adapted birthdate of 20.txt - Nikolaus Wirth

- doc/faq.md
> Update and restructure FAQ

- data/birth-dates/21.txt
> birth date 21

- data/birth-dates/02.txt
Signed-off-by: Robert Cuzencu <robert.cuzencu.mannheim@gmail.com>
> fixed_birth_year_Charles

- data/birth-dates/06.txt
Signed-off-by: Ageda Shiba <agshiba@mail.uni-mannheim.de>
> Fixed birth year for John Backus

- data/birth-dates/03.txt
- data/birth-dates/04.txt
- data/birth-dates/05.txt
> Change made

- data/birth-dates/10.txt
> new change to 10.txt

- data/birth-dates/07.txt
> Tim Berners-Lee birth date

- data/birth-dates/23.txt
- data/birth-dates/32.txt
modify file 32 without create a branch
and modify a file in branch mode but i forget the text number
here to ask to put it into repo
> create new branch modify one file

- data/birth-dates/05.txt
> Exercise 1-05. 

- data/birth-dates/28.txt
> Exercise 1-05

- data/birth-dates/10.txt
I was not sure which number to choose, so I chose 10, the number I got from the "Evaluation of note-taking software".
> Pull Request for Scientific Research Course - De Xing Zhao

- data/birth-dates/37.txt
- data/birth-dates/38.txt
a pull request for birthday from Xueyan Dong
> a pull request for birthday

- data/birth-dates/03.txt
> number 3 changed

- data/birth-dates/09.txt
Changed Birthdate 09 according to the exercise
> Changed Birthdate 09

- data/birth-dates/07.txt
> birth date added

- data/birth-dates/10.txt
> Change birth date of file 10.txt

- data/birth-dates/11.txt
Change the file in /data/birth-dates/11.txt
> Change birth

- data/birth-dates/16.txt
> 16 additing birth year

- data/birth-dates/03.txt
> modify 03.txt

- data/birth-dates/21.txt
> entered year

- data/birth-dates/24.txt
The exact date of Birth for this Man is unknown. So i only added the year of Birth.
> Added Birthyear for Ramon Llull.

- data/birth-dates/04.txt
Birth-date of John Vincent Atanasoff was added
> birth-date added

- data/birth-dates/05.txt
> Birth Date #5 update

- data/birth-dates/07.txt
- Timothy John Berners-Lee (1955-06-08)
> Birthday-7: Birthday of  Berners-Lee

- data/birth-dates/08.txt
The number should correspond to the number from the notes task or ?
> Editing the Birthday to 08.txt

- data/birth-dates/13.txt
I created a pull request for file 5 by mistake, now I'm doing it correctly for my number 13.
> Update 13.txt Gottlob Frege bd

- data/birth-dates/27.txt
Thank you, for reviewing the PR request!
> Leslie B. Lamport's birth year added

- data/birth-dates/10.txt
Added birth date for Edgar F. Codd
> Add birth date

- data/birth-dates/02.txt
I was not sure if you wanted a pull request into the master branch, if not please let me know.
> Added the birthyear of Charles Babbage in file 0-2.txt

- data/birth-dates/02.txt
Please accept my pull request. I updated the txt file for student 2
> Updated the birthdate in the file for student two

- data/birth-dates/11.txt
> changed birth date

- data/birth-dates/06.txt
Updated the birthday of 06 text file according to my sequence
> Updated the birthdate John Backus

- data/birth-dates/10.txt
> Updated Birth date for file 10

- data/birth-dates/09.txt
> Added age | student 9

- data/birth-dates/02.txt
Updates the missing birth year of person 02.
> update birth date 02

- data/birth-dates/01.txt
Corrected the question marks with the correct birth year for my number from the Ilias Etherpad exercise.
> Added the correct birth year for Ada Lovelace.

- data/birth-dates/05.txt
> Add missing birth year for George Boole

- data/birth-dates/11.txt
> Added birthdate for 11.txt

- data/birth-dates/09.txt
Student 09 - "Ayhan Yakici" , for the 09.text i changed the date of birth year for Noam Chomsky.
> Updated by AY

- data/birth-dates/19.txt
> added birth year of Sophie Wilson

- data/birth-dates/15.txt
Changed the birth-date according to my number in "1-03x Evaluation of note-taking software" in ILIAS
> changed: data/birth-dates/15.txt

- data/birth-dates/01.txt
> Completed Number 1

- data/birth-dates/03.txt
As student 3, Jacob C, I have filled in the date for the 3rd person.
> Filled in year for date 3.

- data/birth-dates/16.txt
Year update for file 16.txt in Birth Dates according to task 1-05
> Update Birthday file 16

- data/birth-dates/18.txt
Pull request as per Exercise 1-05
> My new branch

- data/birth-dates/04.txt
added birthdate for file number 04
> Task 1.5 Kai Mechler 4

- data/birth-dates/12.txt
> update birth date

- data/birth-dates/04.txt
Add updated birth dates dataset
> Add updated birth dates dataset

- data/birth-dates/30.txt
- data/birth-dates/32.txt
> Add birthdate

- data/birth-dates/04.txt
> Inserted the correct birth date

- data/birth-dates/28.txt
Added birth year for Rose Dieng-Kuntz
> Test 1 Task 4
